### ISSUE TITLE
CI sometimes ran unnecessarily

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#222]
Running the entire CI pipeline on a commit that changes licenses or github actions workflows is wasteful. We should add some checks to the CI action like the following:
```yaml
on:
  pull_request:
    paths-ignore:
    - '.github/*'
```
We will have to think about which paths are reasonable to skip. See syntax [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet).
